version: "3.9"

services:

  samba:
    image: vimagick/samba
    container_name: samba
    volumes:
        - ./smb.conf:/etc/samba/smb.conf
        - ../share:/samba/share
    net: host
    tty: yes
    restart: always