version: "3"

services:

    samba:
        container_name: samba
        build:
            context: ../
            dockerfile: ./docker/dockerfile
        volumes:
            - ./smb.conf:/etc/samba/smb.conf
            - ../share:/samba/share
        tty: true
        command: nmbd restart -D && smbd restart -FS --no-process-group < /dev/null
        network_mode: host